import { ArrowLeftIcon } from "@heroicons/react/outline";
import Head from "next/head";
import CommentModal from "../../components/CommentModal";
import Sidebar from "../../components/Sidebar";
import Widget from "../../components/Widget";
import Post from "../../components/Post";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Radio from '../../components/Radio';
import { themeState } from '../../atom/ThemeAtom';
import { useRecoilState } from 'recoil';
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { db } from "../../firebase";
import Comment from "../../components/Comments";

export default function PostPage({ newsResult, randomUser}) {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState();
  const [comments, setComments] = useState([]);
  const [select] = useRecoilState(themeState)
  // get the post data

  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [id]
  );

  // get comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [id]);

 useEffect(()=>{
  if(!select){
    document.querySelector('body').style.backgroundColor="black"
    document.querySelector('body').style.color="white"
  }
  if(select){
    document.querySelector('body').style.backgroundColor="white"
    document.querySelector('body').style.color="black"
  }
 },)

  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        <div className={`${select?"border-gray-300":"border-gray-800"} xl:ml-[400px] lg:ml-[250px] border-l border-r  xl:min-w-[650px] sm:ml-[73px] flex-grow max-w-xl w-[100%]`}>
      <div className={`${select?"bg-white border-gray-300":"bg-black border-gray-700"} flex py-2 px-3  sticky z-99  top-0 border-b whitespace-nowrap `}>
        <h2 className={`${select?"text-black":"text-white "}sm:text-lg xl:text-xl cursor-pointer font-bold `}>Comments</h2>
        <div className="ml-auto mr-7 flex items-center xs:text-sm xs:items-start justify-center w-9 h-9"><Radio/></div>
      </div>
          <Post id={id} post={post} />
          {comments.length > 0 && (
            <div className={`${select?"text-black":"text-white"}`}>
                {comments.map((comment) => (
                  <div 
                    key={comment.id}
                  >
                    <Comment
                      key={comment.id}
                      commentId={comment.id}
                      originalPostId={id}
                      comment={comment.data()}
                    />
                  </div>
                ))}
            </div>
          )}
        </div>

        {/* Widgets */}

        <Widget newsResult={newsResult.articles} randomUser={randomUser.results}/>

        {/* Modal */}

        <CommentModal />
      </main>
    </div>
  );
}

export async function getServerSideProps(){
    const newsResult=await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then(res=>res.json())
       
    const randomUser=await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture").then((res)=>res.json())
    return{
      props:{
        newsResult,
        randomUser,
      }
    }
  } 