import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import Feed from './../components/Feed';
import Widget from './../components/Widget';


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className='flex min-h-screen max-w-7xl m-auto'>
    {/* sidebar */}
     <Sidebar />

    {/* feed */}
      <Feed/>
    {/* modal */}

    {/* widget */}
    <Widget/>
    </main>

    </>
  )
}
